#!/usr/bin/env bash

set -euo pipefail

arch=$(uname -m)
base=https://github.com/koalaman/shellcheck/releases/download
: "${version:=v0.9.0}"

wget -nv -O- \
  "${base}/${version}/shellcheck-${version}.linux.${arch}.tar.xz" |
  tar -xJv
mv -f "shellcheck-${version}/shellcheck" ~/.local/bin
rm -rf "shellcheck-${version}"

command -v shellcheck && shellcheck --version
