name: Docker

"on": workflow_dispatch

jobs:
  build_push:
    name: Build and push Docker image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Retrieve sysmon-mqtt version
        id: sysmon
        run: |
          semver=$(
            ./sysmon.sh --version | \
            grep -oE '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+(-[-a-z0-9\.]+)?'
          )
          echo semver="v$semver" >> "$GITHUB_OUTPUT"
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            thijsputman/sysmon-mqtt
            ghcr.io/thijsputman/sysmon-mqtt
          # yamllint disable rule:line-length
          tags: |
            type=sha
            type=semver,pattern={{version}},value=${{ steps.sysmon.outputs.semver }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.sysmon.outputs.semver }}
            type=semver,pattern={{major}},value=${{ steps.sysmon.outputs.semver }}
            type=ref,event=pr,prefix=pr-
            type=edge,branch=develop
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          # yamllint enable rule:line-length
          flavor: |
            latest=false
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
          # Force the Docker-action to use a local context – otherwise it'll
          # clone the repo again from GitHub. This is wasteful as we do a
          # checkout anyway to get sysmon's version number...
          # Also, this is relevant for local "gh act" runs where we want local/
          # non-committed changes to be picked up (this is done in act by
          # overriding the default "Checkout code"-action).
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
